import polars as pl

# Web Sales Schema
web_sales_schema = {
    "ws_sold_date_sk": pl.Int64,
    "ws_sold_time_sk": pl.Int64,
    "ws_ship_date_sk": pl.Int64,
    "ws_item_sk": pl.Int64,
    "ws_bill_customer_sk": pl.Int64,
    "ws_bill_cdemo_sk": pl.Int64,
    "ws_bill_hdemo_sk": pl.Int64,
    "ws_bill_addr_sk": pl.Int64,
    "ws_ship_customer_sk": pl.Int64,
    "ws_ship_cdemo_sk": pl.Int64,
    "ws_ship_hdemo_sk": pl.Int64,
    "ws_ship_addr_sk": pl.Int64,
    "ws_web_page_sk": pl.Int64,
    "ws_web_site_sk": pl.Int64,
    "ws_ship_mode_sk": pl.Int64,
    "ws_warehouse_sk": pl.Int64,
    "ws_promo_sk": pl.Int64,
    "ws_order_number": pl.Int64,
    "ws_quantity": pl.Int32,
    "ws_wholesale_cost": pl.Float64,
    "ws_list_price": pl.Float64,
    "ws_sales_price": pl.Float64,
    "ws_ext_discount_amt": pl.Float64,
    "ws_ext_sales_price": pl.Float64,
    "ws_ext_wholesale_cost": pl.Float64,
    "ws_ext_list_price": pl.Float64,
    "ws_ext_tax": pl.Float64,
    "ws_coupon_amt": pl.Float64,
    "ws_ext_ship_cost": pl.Float64,
    "ws_net_paid": pl.Float64,
    "ws_net_paid_inc_tax": pl.Float64,
    "ws_net_paid_inc_ship": pl.Float64,
    "ws_net_paid_inc_ship_tax": pl.Float64,
    "ws_net_profit": pl.Float64
}

# Date Dimension Schema
date_dim_schema = {
    "d_date_sk": pl.Int64,
    "d_date_id": pl.Utf8,
    "d_date": pl.Date,
    "d_month_seq": pl.Int32,
    "d_week_seq": pl.Int32,
    "d_quarter_seq": pl.Int32,
    "d_year": pl.Int32,
    "d_dow": pl.Int32,
    "d_moy": pl.Int32,
    "d_dom": pl.Int32,
    "d_qoy": pl.Int32,
    "d_fy_year": pl.Int32,
    "d_fy_quarter_seq": pl.Int32,
    "d_fy_week_seq": pl.Int32,
    "d_day_name": pl.Utf8,
    "d_quarter_name": pl.Utf8,
    "d_holiday": pl.String,
    "d_weekend": pl.String,
    "d_following_holiday": pl.String,
    "d_first_dom": pl.Int32,
    "d_last_dom": pl.Int32,
    "d_same_day_ly": pl.Int32,
    "d_same_day_lq": pl.Int32,
    "d_current_day": pl.String,
    "d_current_week": pl.String,
    "d_current_month": pl.String,
    "d_current_quarter": pl.String,
    "d_current_year": pl.String
}

# Web Returns Schema
web_returns_schema = {
    "wr_returned_date_sk": pl.Int64,
    "wr_returned_time_sk": pl.Int64,
    "wr_item_sk": pl.Int64,
    "wr_refunded_customer_sk": pl.Int64,
    "wr_refunded_cdemo_sk": pl.Int64,
    "wr_refunded_hdemo_sk": pl.Int64,
    "wr_refunded_addr_sk": pl.Int64,
    "wr_returning_customer_sk": pl.Int64,
    "wr_returning_cdemo_sk": pl.Int64,
    "wr_returning_hdemo_sk": pl.Int64,
    "wr_returning_addr_sk": pl.Int64,
    "wr_web_page_sk": pl.Int64,
    "wr_reason_sk": pl.Int64,
    "wr_order_number": pl.Int64,
    "wr_return_quantity": pl.Int32,
    "wr_return_amt": pl.Float64,
    "wr_return_tax": pl.Float64,
    "wr_return_amt_inc_tax": pl.Float64,
    "wr_fee": pl.Float64,
    "wr_return_ship_cost": pl.Float64,
    "wr_refunded_cash": pl.Float64,
    "wr_reversed_charge": pl.Float64,
    "wr_store_credit": pl.Float64,
    "wr_net_loss": pl.Float64
}

# Customer Address Schema
customer_address_schema = {
    "ca_address_sk": pl.Int64,
    "ca_address_id": pl.Utf8,
    "ca_street_number": pl.Utf8,
    "ca_street_name": pl.Utf8,
    "ca_street_type": pl.Utf8,
    "ca_suite_number": pl.Utf8,
    "ca_city": pl.Utf8,
    "ca_county": pl.Utf8,
    "ca_state": pl.Utf8,
    "ca_zip": pl.Utf8,
    "ca_country": pl.Utf8,
    "ca_gmt_offset": pl.Float64,
    "ca_location_type": pl.Utf8
}

# Web Site Schema
web_site_schema = {
    "web_site_sk": pl.Int64,
    "web_site_id": pl.Utf8,
    "web_rec_start_date": pl.Date,
    "web_rec_end_date": pl.Date,
    "web_name": pl.Utf8,
    "web_open_date_sk": pl.Int64,
    "web_close_date_sk": pl.Int64,
    "web_class": pl.Utf8,
    "web_manager": pl.Utf8,
    "web_mkt_id": pl.Int32,
    "web_mkt_class": pl.Utf8,
    "web_mkt_desc": pl.Utf8,
    "web_market_manager": pl.Utf8,
    "web_company_id": pl.Int32,
    "web_company_name": pl.Utf8,
    "web_street_number": pl.Utf8,
    "web_street_name": pl.Utf8,
    "web_street_type": pl.Utf8,
    "web_suite_number": pl.Utf8,
    "web_city": pl.Utf8,
    "web_county": pl.Utf8,
    "web_state": pl.Utf8,
    "web_zip": pl.Utf8,
    "web_country": pl.Utf8,
    "web_gmt_offset": pl.Float64,
    "web_tax_percentage": pl.Float64
}